"""Add todo table date fields

Revision ID: a941097e3c2e
Revises: dda65a1d96bb
Create Date: 2021-02-07 00:42:01.675259

"""
from alembic import op
import sqlalchemy as sa


revision = "a941097e3c2e"
down_revision = "dda65a1d96bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "todo",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "todo", sa.Column("due_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "todo", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todo", "updated_at")
    op.drop_column("todo", "due_at")
    op.drop_column("todo", "created_at")
    # ### end Alembic commands ###
